name: "Build vcpkg-example"

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs:
  build-linux:
    name: "Build on Linux"
    runs-on: "ubuntu-18.04"
    steps:
      - uses: "actions/checkout@v2"
      - id: "get-vcpkg"
        uses: "strega-nil/get-vcpkg"
      - name: "Configure"
        run: "cmake -B build -S . -DCMAKE_CXX_COMPILER=clang++-9 -DCMAKE_TOOLCHAIN_FILE=${{ steps.get-vcpkg.outputs.vcpkg-root }}/buildsystem/scripts/vcpkg.cmake"
      - name: "Build"
        run: "cmake --build build"
